# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Copy secrets
      run: echo "<?xml version=\"1.0\" encoding=\"utf-8\"?>
                  <resources>
                    <string name=\"com.twitter.sdk.android.CONSUMER_KEY\">${{secrets.TWITTER_CONSUMER_KEY}}</string>
                    <string name=\"com.twitter.sdk.android.CONSUMER_SECRET\">${{secrets.TWITTER_CONSUMER_SECRET}}</string>
                  </resources>" >> app/src/main/res/values/secrets.xml
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
